name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      VC_DIR: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
      MSYS: 'D:\'
    steps:   
    - name: Setup Toolchain
      run: |
        curl -OL https://mpc-be.org/MSYS/MSYS_MinGW-w64_GCC_1120_x86-x64.7z
        &'C:\Program Files\7-Zip\7z.exe' x -y *.7z -o'D:\MSYS' 
        
    - name: Set path
      shell: cmd
      run: |
        set Path=${{ env.VC_DIR }};${{ env.MSYS }}MSYS\bin;${{ env.MSYS }}MSYS\mingw\bin;
        set Path=%Path%C:\hostedtoolcache\windows\Python\3.9.9\x64;C:\Program Files\7-Zip;C:\Program Files\Git;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PowerShell\7\;
        echo CLEAN_PATH=%path% > %GITHUB_ENV%    
    
    - name: Set up Nasm
      uses: ilammy/setup-nasm@v1      
      with:
        destination: ${{env.VC_DIR}}     
 
    - name: Install Yasm
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -OutFile ${{ env.MSYS }}MSYS\bin\yasm.exe -UseBasicParsing

    - name: Install Microsoft Visual C++ 2010 redistributable packages
      shell: powershell
      run: |
        choco install vcredist-alls
   
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0    
        submodules: true           

    - name: Copy the files libgcc.a and libmingwex.a 
      env:
        MPCBE_MSYS: ${{ env.MSYS }}MSYS
        MPCBE_MINGW: ${{ env.MSYS }}MSYS\mingw     
        PATH: ${{env.CLEAN_PATH}}
      shell: cmd
      run: |
        set PATH
        ./update_gcc.bat  

    - name: Build the package (x64)
      env:
        MPCBE_MSYS: ${{ env.MSYS }}MSYS
        MPCBE_MINGW: ${{ env.MSYS }}MSYS\mingw
        PATH: ${{env.CLEAN_PATH}}
      shell: cmd
      run: |
        set PATH
        ./build.bat x64 Release VS2022 Packages
        
    - name: Upload 7z archives (x64)
      uses: actions/upload-artifact@v2
      with:
        name: MPC-BE 
        path: _bin/*x64.7z   
