name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      VC_DIR: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
      MSYS: 'D:\'
    steps:   
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        location: ${{ env.MSYS }}
        install: base-devel autotools yasm 
   
    - name: Set path
      shell: cmd
      run: |
        set Path=${{ env.VC_DIR }};${{ env.MSYS }}msys64\mingw\bin;${{ env.MSYS }}msys64\usr\bin;
        set Path=%Path%C:\hostedtoolcache\windows\Python\3.9.9\x64;C:\Program Files\7-Zip;C:\Program Files\Git;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PowerShell\7\;
        echo CLEAN_PATH=%path% > %GITHUB_ENV% 

    - name: Setup Toolchain
      run: |
        curl -OL https://mpc-be.org/MSYS/MSYS_MinGW-w64_GCC_1120_x86-x64.7z
        &'C:\Program Files\7-Zip\7z.exe' x -y *.7z -o'D:\msys64'    
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0    
        submodules: true
      
    - name: Checkout modules
      run: git submodule update --init --recursive            

    - name: Copy the files libgcc.a and libmingwex.a 
      env:
        MPCBE_MSYS: ${{ env.MSYS }}msys64
        MPCBE_MINGW: ${{ env.MSYS }}msys64\mingw 
        MSYSTEM: MINGW32
        MPCBE_GIT: 'C:\Program Files\Git'
        PATH: ${{env.CLEAN_PATH}}
      shell: cmd
      run: |
        set PATH
        ./update_gcc.bat  

    - name: Build the package (x64)
      env:
        MPCBE_MSYS: ${{ env.MSYS }}msys64
        MPCBE_MINGW: ${{ env.MSYS }}msys64\mingw
        MSYSTEM: MINGW32
        MPCBE_GIT: 'C:\Program Files\Git'
        PATH: ${{env.CLEAN_PATH}}
      shell: cmd
      run: |
        set PATH
        ./build.bat x64 Release VS2022 Packages
        
    - name: Upload 7z archives (x64)
      uses: actions/upload-artifact@v2
      with:
        name: MPC-BE 
        path: _bin/*x64.7z   
