name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      VC_DIR: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
    steps:   
    - name: Setup Toolchain
      run: |
        curl -OL https://mpc-be.org/MSYS/MSYS_MinGW-w64_GCC_1220_x86-x64.7z
        &'C:\Program Files\7-Zip\7z.exe' x *.7z -o'D:\MSYS' 

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set Path
      shell: cmd
      run: |
        set path=${{ env.VC_DIR }};D:\MSYS\bin;D:\MSYS\mingw\bin;
        set path=%path%$pythonLocation;C:\Program Files\7-Zip;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PowerShell\7\;
        echo CLEAN_PATH=%path% > %GITHUB_ENV%        
 
    - name: Install Yasm
      run: |
        curl -OL http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe 
        mv yasm-1.3.0-win64.exe C:\Windows\yasm.exe  

    - name: Install Microsoft Visual C++ 2010 redistributable packages
      shell: powershell
      run: |
        choco install vcredist2010
 
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0    
        submodules: true
      
    - name: Checkout modules
      run: git submodule update --init --recursive             

    - name: Copy the files libgcc.a and libmingwex.a 
      env:
        MPCBE_MSYS: D:\MSYS
        MPCBE_MINGW: D:\MSYS\mingw     
        PATH: ${{env.CLEAN_PATH}}
      shell: cmd
      run: |
        ./update_gcc.bat  

    - name: Build the package (x64)
      env:
        MPCBE_MSYS: D:\MSYS
        MPCBE_MINGW: D:\MSYS\mingw
        PATH: ${{env.CLEAN_PATH}}
      shell: cmd
      run: |
        ./build.bat Build x64 MPC-BE Release Zip

    - name: Get current timestamp      
      id: timestamp
      run: echo "::set-output name=date::$(date +%Y-%m-%d)"  
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:       
        tag_name: MPC-BE-${{ steps.timestamp.outputs.date }}
        name: ${{ steps.timestamp.outputs.date }}
        files: _bin/Packages/**/*x64.7z  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
